"""empty message

Revision ID: 2365c6a2f1ee
Revises: 9a0e244d1260
Create Date: 2022-09-07 20:07:33.812756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2365c6a2f1ee'
down_revision = '9a0e244d1260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_column('date_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_used', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
